name: Build and deploy Vue.js & ASP.Net Core app to Railway

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Frontend build
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install
          npm ci
          npm install axios
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      # After frontend is built, copy build artifacts to backend wwwroot
      - name: Copy frontend build artifacts to backend
        run: |
          Copy-Item -Path ./frontend/dist/* -Destination ./backend/wwwroot -Recurse -Force
        shell: pwsh

      # Backend build
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release ./backend

      - name: dotnet publish
        run: dotnet publish -c Release -o ./myapp ./backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: ./myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: myapp

      - name: Deploy to Railway
        run: npx railway up
        env:
          RAILWAY_API_TOKEN: ${{ env.RAILWAY_API_TOKEN }}